trans_client={
    "modelname":"Clients",
    'list' : 'Liste des clients',
    "new":"Ajouter client",
    "update":"Modifier client",

    "code": "Code",
    "name": "Nom",
    "email": "Email",
    "phone": "Phone",
    "fix": "Fix",
    "adress": "Adresse",
    "rc": "RC",
    "cnss": "CNSS",
    "ifescale": "Identification fiscal",
    "ice": "ICE",
    "active": "Activé",
    "plafond": "Plafond de crédit",
    "type": "Type",
    "type_personn": "Personne",
    "type_company": "Entreprise",
    "type_prospect": "Prospect",
    "type_partner": "Partenaire",
    "type_reseller": "Revendeur",
    "type_vendor": "Vendeur",
    "type_other": "Autre",

    "name_validation":"Le nom est obligatoire.",
};