trans_global={
	'actions': 'Actions',
	'annuler' : 'Annuler',
	'valider' : 'Enregistrer',
	'add' : 'Ajouter',
	'submit' : 'Submit',
    "fermer":"Fermer",
	'modifier' : 'Modifier',
    "dupliquer":"Dupliquer",
    "rechercher":"Rechercher",
    "close":"Fermer",
	'oui' : 'Oui',
	'no' : 'Non',
	'ok' : 'Ok',
	'pageaccueil' : 'Page d\'accueil',
	'delete':'Supprimer',
	'archive':'Archiver',
	'forcedelete':'Supprimer',
    'confirm_delete': 'Êtes-vous sûr ?',
    'confirm_delete_text': 'Faites attention, cette action est irreversible.',
    'The given data was invalid.': 'Les données fournies n\'étaient pas valides ',
	'choix':'Choisissez',

	'relogin':'Ré-authentification',
	'nopermission':'Aucune autorisation',
	'nopermissiontext':'vous n\'avez pas le droit pour consulter cette partie',

	'Unauthenticated.':'Non authentifié',
	'unauthenticatedtext':'vous devez être authentifié pour accéder à cette page',
	'Saisiedemande':'Saisie de demande',
	'liens':'Liens',
	'demandejour':'Demandes du Jour',
	'valideimprimerenvoyer' : 'Valide Et Imprimer / Envoyer',
	'imprimerenvoyer' : 'Imprimer / Envoyer',
	'archiver' : 'Archiver',
	'carte' : 'Carte',
	'intervenants':'Intervenants',
	'ajouter':'Ajouter',
	'update':'Modifier',
	'show':'Afficher',
	'date':'Date',
    'type':'Type',
    'liens':'Liens',
    'accueil':'Accueil',
    'saisiedemande':'Saisir une demande',
    'demandesjour':'Demandes du Jour',
    'rechdemende':'Rech. demande',
    'rechdemendearchivee':'Rech. demande archivée',
    'saisieresultats':'Saisir les résultats',
    'nodata':'Aucun Résultat Trouvé ...',
	"motpasse": "Mot de Passe :",
	"votreemail" : "Nom d\'utilisateur :",
	"login" : "Connexion",
    "filter":"Filter",
	"ans":"An(s)",
	"moiss":"Mois",
	"fieldeconfirm":"Confirmer les Champs",
	"cofirme":"Saisir le code",
	"confrme":"Saisir le nom ",
	"fieldconfirm":"Confirmer les Champs",
	"cofirm":"Saisir le code",
	"confrm":"Saisir le nom",
	"masculin":"Masculin",
	"feminin":"Féminin",
	"filedsrequired":"les Champs suivants sont obligatoires: :champs ",
	"required":"Champ :champ est Obligatoire",
	"existe":"Champ :champ n'existe pas",
	"loading":"Chargement en cours; veuillez patienter...",
	"home":"Accueil",
	"warning_alert":"veuillez sélectionner les patients à fusionner.",
	"confirm_fusioner":"fusionner le patient",
	"fusioner_text":"Êtes-vous sûr ? Cette action est irréversible.",

	'main' : 'Main',
	'post' : 'Post',
	'tele' : 'Télé',
	'whatsapp' : 'WhatsApp',
	'fax' : 'Fax',
	'email' : 'E-mail',
	'sms' : 'SMS',
	'upload' : 'Télécharger',

	'afficherobject' : 'Afficher détails de :object',

	//mois :
	'mois' :[
	    'Janvier',
	    'Février',
	    'Mars',
	    'Avril'	,
	    'Mai',
	    'Juin'	,
	    'Juillet',
	    'Août',
	    'Septembre'	,
	    'Octobre'	,
	    'Novembre',
	    'Décembre'
	],
	// les jours :
	'jours' : [
		'Dim',
		'Lun',
		'Mar', 
		'Mer',
		'Jeu',
		'Ven',
		'Sam', 
	],
	'supprimer':'Supprimer',
	'CREATE':'Création',
	'UPDATE':'Modification',
	'DELETE':'Suppression',
	'LIST':'Listage',
	'VALIDATIONTECH':'Validation technique',
	'VALIDATIONBIO':' Validation biologique',
	'DEVALIDATION':' Dévalidation',
	'ARCHIVEES':'Archivées ',
	'REMISE':'Remise',
	'FACTURECAISSE':'Facturation caisse',
	'FACTURECORRESPONDANT':'Facturation correspondant',
	'FACTUREMUTUELLE':'Facturation mutuelle',
	'PATIENT':'Patient',
	'JOURNALCAISSE':'Journal caisse',
	'GENERAL':'General',
	'EXPORTRESULTATS':'Export résultats',

	'etats' : {
		'pendding':'en attendant',
		'done':'terminé',
		'failed':'échoué',
	},
	'closeall':'Fermer tous'
};