trans_product={
    "modelname":"Produits",
    'list' : 'Liste des produits',
    "new":"Ajouter produit",
    "update":"Modifier produit",
    "reference": "Référence",
    "barcode": "Code à Barre",
    "name": "Nom",
    "purchase_price": "Prix d\'achat",
    "price": "Prix de vent",
    "description": "Description",
    "unite": "Unité",
    "picture": "Image",
    "color": "Color",
    "categorie_id": "Categorie",
    "supplier_id": "Fournisseur",
    "shelf_id": "Étage",
    "stock": "Qté en Stock",
    "sold": "Qté vendu",
    "notes": "Notes",

    "reference_validation":"Le référence est obligatoire.",
    "name_validation":"Le nom est obligatoire.",
    "price_validation":"Le prix de vent est obligatoire.",
};